# ios-simulator.toolchain.cmake

# Tell CMake we are cross-compiling for Apple platforms
set(CMAKE_SYSTEM_NAME iOS)
set(CMAKE_SYSTEM_PROCESSOR arm64)

set(CMAKE_OSX_SYSROOT iphonesimulator)

set(CMAKE_OSX_ARCHITECTURES "arm64" CACHE STRING "")

set(CMAKE_OSX_DEPLOYMENT_TARGET "12.0" CACHE STRING "")

set(CMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_REQUIRED NO)
set(CMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_ALLOWED NO)
set(CMAKE_XCODE_ATTRIBUTE_CODE_SIGN_IDENTITY "")